baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jpaulmora.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-paginate-multiple
  - jekyll-sitemap
  - jekyll/tagging
  

paginate_multiple:
  - paginate: 2
    paginate_path: '/inicio/page:num/'
    sub_dir: '/es'
  - paginate: 2
    paginate_path: '/index/page:num/'
    sub_dir: '/en'
    



# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages


# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed

# Multilang
t:
  en:
    home:
      name: "Home"
      url: "/index"
    about:
      name: "About"
      url: "/about/"
  es:
    home:
      name: "Inicio"
      url: "/inicio"
    about:
      name: "Acerca de"
      url: "/acerca-de"